CRITICAL - 2024-12-18 19:55:34 --> CodeIgniter\Filters\Exceptions\FilterException: "apiFilter" filter must have a matching alias defined.
[Method: GET, Route: api/guests]
in SYSTEMPATH\Filters\Filters.php on line 495.
 1 SYSTEMPATH\Filters\Filters.php(495): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('apiFilter')
 2 SYSTEMPATH\Filters\Filters.php(547): CodeIgniter\Filters\Filters->enableFilter('apiFilter', 'before')
 3 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\Filters\Filters->enableFilters([...], 'before')
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-18 19:55:42 --> CodeIgniter\Filters\Exceptions\FilterException: "apiFilter" filter must have a matching alias defined.
[Method: GET, Route: api/guests]
in SYSTEMPATH\Filters\Filters.php on line 495.
 1 SYSTEMPATH\Filters\Filters.php(495): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('apiFilter')
 2 SYSTEMPATH\Filters\Filters.php(547): CodeIgniter\Filters\Filters->enableFilter('apiFilter', 'before')
 3 SYSTEMPATH\CodeIgniter.php(469): CodeIgniter\Filters\Filters->enableFilters([...], 'before')
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-18 20:01:19 --> CodeIgniter\Database\Exceptions\DataException: There is no data to insert.
[Method: POST, Route: api/guests/create]
in SYSTEMPATH\BaseModel.php on line 1833.
 1 SYSTEMPATH\BaseModel.php(1833): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\BaseModel.php(806): CodeIgniter\BaseModel->transformDataToArray([], 'insert')
 3 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([], true)
 4 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert([])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-18 20:12:18 --> CodeIgniter\Database\Exceptions\DataException: There is no data to update.
[Method: PUT, Route: api/guests/update/2]
in SYSTEMPATH\BaseModel.php on line 1011.
 1 SYSTEMPATH\BaseModel.php(1011): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(865): CodeIgniter\BaseModel->update([...], [])
 3 APPPATH\Controllers\API\Guests.php(30): CodeIgniter\Model->update('2', [...])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->update('2')
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-12-18 20:54:05 --> mysqli_sql_exception: Unknown column 'create_date' in 'field list' in C:\xampp\htdocs\clarika\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\clarika\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `gu...', 0)
#1 C:\xampp\htdocs\clarika\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `gu...')
#2 C:\xampp\htdocs\clarika\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `gu...')
#3 C:\xampp\htdocs\clarika\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `gu...', Array, false)
#4 C:\xampp\htdocs\clarika\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\clarika\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\clarika\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\clarika\app\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\clarika\system\CodeIgniter.php(933): App\Controllers\API\Guests->create()
#9 C:\xampp\htdocs\clarika\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
#10 C:\xampp\htdocs\clarika\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\clarika\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\clarika\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\clarika\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-12-18 20:54:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'create_date' in 'field list'
[Method: POST, Route: api/guests/create]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `guests` (`name`, `email`, `phone`, `create_date`, `update_date`) VALUES (:name:, :email:, :phone:, :create_date:, :update_date:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-18 20:54:05 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'create_date' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `guests` (`name`, `email`, `phone`, `create_date`, `update_date`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:54:05\', \'2024-12-18 20:54:05\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `guests` (`name`, `email`, `phone`, `create_date`, `update_date`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:54:05\', \'2024-12-18 20:54:05\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `guests` (`name`, `email`, `phone`, `create_date`, `update_date`) VALUES (:name:, :email:, :phone:, :create_date:, :update_date:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-18 20:54:05 --> [Caused by] mysqli_sql_exception: Unknown column 'create_date' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `guests` (`name`, `email`, `phone`, `create_date`, `update_date`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:54:05\', \'2024-12-18 20:54:05\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `guests` (`name`, `email`, `phone`, `create_date`, `update_date`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:54:05\', \'2024-12-18 20:54:05\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `guests` (`name`, `email`, `phone`, `create_date`, `update_date`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:54:05\', \'2024-12-18 20:54:05\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `guests` (`name`, `email`, `phone`, `create_date`, `update_date`) VALUES (:name:, :email:, :phone:, :create_date:, :update_date:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-12-18 20:58:08 --> mysqli_sql_exception: Duplicate entry 'nandos@gmail.com' for key 'email' in C:\xampp\htdocs\clarika\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\clarika\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `gu...', 0)
#1 C:\xampp\htdocs\clarika\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `gu...')
#2 C:\xampp\htdocs\clarika\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `gu...')
#3 C:\xampp\htdocs\clarika\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `gu...', Array, false)
#4 C:\xampp\htdocs\clarika\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\clarika\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\clarika\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\clarika\app\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\clarika\system\CodeIgniter.php(933): App\Controllers\API\Guests->create()
#9 C:\xampp\htdocs\clarika\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
#10 C:\xampp\htdocs\clarika\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\clarika\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\clarika\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\clarika\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-12-18 20:58:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'nandos@gmail.com' for key 'email'
[Method: POST, Route: api/guests/create]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (:name:, :email:, :phone:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-18 20:58:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'nandos@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:58:08\', \'2024-12-18 20:58:08\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:58:08\', \'2024-12-18 20:58:08\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (:name:, :email:, :phone:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-18 20:58:08 --> [Caused by] mysqli_sql_exception: Duplicate entry 'nandos@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:58:08\', \'2024-12-18 20:58:08\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:58:08\', \'2024-12-18 20:58:08\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandos\', \'nandos@gmail.com\', \'2354343435\', \'2024-12-18 20:58:08\', \'2024-12-18 20:58:08\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (:name:, :email:, :phone:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-12-18 20:58:28 --> mysqli_sql_exception: Duplicate entry 'nandoss@gmail.com' for key 'email' in C:\xampp\htdocs\clarika\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 C:\xampp\htdocs\clarika\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `gu...', 0)
#1 C:\xampp\htdocs\clarika\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `gu...')
#2 C:\xampp\htdocs\clarika\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `gu...')
#3 C:\xampp\htdocs\clarika\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `gu...', Array, false)
#4 C:\xampp\htdocs\clarika\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\clarika\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\clarika\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\clarika\app\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
#8 C:\xampp\htdocs\clarika\system\CodeIgniter.php(933): App\Controllers\API\Guests->create()
#9 C:\xampp\htdocs\clarika\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
#10 C:\xampp\htdocs\clarika\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\clarika\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\clarika\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\clarika\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-12-18 20:58:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'nandoss@gmail.com' for key 'email'
[Method: POST, Route: api/guests/create]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (:name:, :email:, :phone:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-18 20:58:28 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'nandoss@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandsos\', \'nandoss@gmail.com\', \'23543434435\', \'2024-12-18 20:58:28\', \'2024-12-18 20:58:28\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandsos\', \'nandoss@gmail.com\', \'23543434435\', \'2024-12-18 20:58:28\', \'2024-12-18 20:58:28\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (:name:, :email:, :phone:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-12-18 20:58:28 --> [Caused by] mysqli_sql_exception: Duplicate entry 'nandoss@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandsos\', \'nandoss@gmail.com\', \'23543434435\', \'2024-12-18 20:58:28\', \'2024-12-18 20:58:28\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandsos\', \'nandoss@gmail.com\', \'23543434435\', \'2024-12-18 20:58:28\', \'2024-12-18 20:58:28\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (\'nandsos\', \'nandoss@gmail.com\', \'23543434435\', \'2024-12-18 20:58:28\', \'2024-12-18 20:58:28\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `guests` (`name`, `email`, `phone`, `created_at`, `updated_at`) VALUES (:name:, :email:, :phone:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\API\Guests.php(13): CodeIgniter\Model->insert(Object(stdClass))
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\API\Guests->create()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\Guests))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
